language: c
sudo: false
compiler:
  - clang
  - gcc
arch: ppc64le
addons:
  apt:
    packages:
    - git
    - make
    - autoconf
    - libtool
    - pkg-config
    - libncurses5-dev
    - libreadline6-dev
    - zlib1g-dev
    - uuid-dev
    - libxml2-dev
    - libglib2.0-dev
    - libraptor2-dev
    - librasqal3-dev
# install: make get-deps

script: 
  - |
      if [{"Travis_CPU_ARCH" == "ppc64le"}]; then
      sudo chown -R 777 $USER:$GROUP 
  - ./autogen.sh && ./configure && make && make test
